version: '3.7'
services:
  intro-api:
    depends_on:
      - intro-db
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_CONNECTION_STRING=mongodb://intro-db:27017/
      - TOKEN_KEY=howdy
  intro-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: